export const electricianProducts: ProductType[] = [
    {
        id: 'prod-001',
        sku: 'SOL-HELM-2024',
        name: 'Solar-Powered Safety Helmet',
        description: 'Hard hat with integrated solar-powered LED lighting for low-light conditions',
        price: 89.99,
        category: 'solar',
        type: 'helmet',
        isOnSale: true,
        inStock: true,
        rating: 4.5,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-002',
        sku: 'WIND-HARN-5500',
        name: 'Wind-Resistant Safety Harness',
        description: 'Heavy-duty fall protection harness designed for wind turbine technicians',
        price: 249.99,
        category: 'wind',
        type: 'safety-belt',
        isOnSale: false,
        inStock: true,
        rating: 4.8,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-003',
        sku: 'GEN-GLOVE-3300',
        name: 'Insulated Electrician Gloves',
        description: 'Class 00 rubber insulating gloves with leather protectors',
        price: 75.5,
        category: 'general',
        type: 'gloves',
        isOnSale: true,
        inStock: true,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-004',
        sku: 'SOL-KIT-8800',
        name: 'Solar Panel Installation Kit',
        description: 'Complete toolkit for solar panel installation including insulated tools',
        price: 199.99,
        category: 'solar',
        type: 'tool',
        isOnSale: false,
        inStock: true,
        rating: 4.7,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-005',
        sku: 'WIND-VEST-2200',
        name: 'Wind Farm Safety Vest',
        description: 'High-visibility safety vest with reflective strips for wind farm environments',
        price: 45.99,
        category: 'wind',
        type: 'clothing',
        isOnSale: true,
        inStock: false,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-006',
        sku: 'GEN-HELM-7700',
        name: 'Arc Flash Protective Helmet',
        description: 'Electrical hazard helmet with face shield and hearing protection',
        price: 129.99,
        category: 'general',
        type: 'helmet',
        isOnSale: false,
        inStock: true,
        rating: 4.9,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-007',
        sku: 'SOL-CABLE-4400',
        name: 'Solar Cable Management System',
        description: 'Weatherproof cable trays and management for solar installations',
        price: 89.99,
        category: 'solar',
        type: 'tool',
        isOnSale: true,
        inStock: true,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-008',
        sku: 'WIND-BELT-6600',
        name: 'Tower Climbing Safety Belt',
        description: 'Specialized safety belt for wind turbine tower climbing',
        price: 179.99,
        category: 'wind',
        type: 'safety-belt',
        isOnSale: false,
        inStock: true,
        rating: 4.6,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-009',
        sku: 'SOL-METER-1100',
        name: 'Solar Installation Multimeter',
        description: 'Digital multimeter with solar panel testing capabilities',
        price: 149.99,
        category: 'solar',
        type: 'tool',
        isOnSale: true,
        inStock: true,
        rating: 4.4,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-010',
        sku: 'WIND-TOOL-9900',
        name: 'Wind Turbine Tool Set',
        description: 'Specialized tools for wind turbine maintenance and repair',
        price: 349.99,
        category: 'wind',
        type: 'tool',
        isOnSale: false,
        inStock: true,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    }
];
