export const electricianProducts: ProductType[] = [
    {
        id: 'prod-001',
        sku: 'SOL-HELM-2024',
        name: 'Fall Protection Distributors Standing Seam Roof Anchor SSRA1',
        description: 'Hard hat with integrated solar-powered LED lighting for low-light conditions',
        price: 89.99,
        category: 'solar',
        type: 'helmet',
        isOnSale: true,
        inStock: true,
        isBackOrder: false,
        rating: 4.5,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/s/s/ssra1.png'
    },
    {
        id: 'prod-002',
        sku: 'WIND-HARN-5500',
        name: 'Petzl CSA/ANSI Vertex Helmet - Canadian Version',
        description: 'Heavy-duty fall protection harness designed for wind turbine technicians',
        price: 249.99,
        category: 'wind',
        type: 'safety-belt',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.8,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/w/h/white-vent.jpg'
    },
    {
        id: 'prod-003',
        sku: 'GEN-GLOVE-3300',
        name: `Harken Deluxe Bosun's Chair`,
        description: 'Class 00 rubber insulating gloves with leather protectors',
        price: 75.5,
        category: 'general',
        type: 'gloves',
        isOnSale: true,
        inStock: true,
        isBackOrder: true,
        rating: 4.2,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/h/k/hk-10177640.jpg'
    },
    {
        id: 'prod-004',
        sku: 'SOL-KIT-8800',
        name: 'French Creek Deluxe Work Seat - 21 inch X 16 Inch',
        description: 'Complete toolkit for solar panel installation including insulated tools',
        price: 199.99,
        category: 'solar',
        type: 'tool',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.7,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/f/c/fc-4151.jpg'
    },
    {
        id: 'prod-005',
        sku: 'WIND-VEST-2200',
        name: 'Elk River PeregrineRAS Platinum Tower Harness with Aluminum D-Rings',
        description: 'High-visibility safety vest with reflective strips for wind farm environments',
        price: 45.99,
        category: 'wind',
        type: 'clothing',
        isOnSale: true,
        inStock: false,
        isBackOrder: true,
        rating: 3.9,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/m/n/mn1_000581.jpg'
    },
    {
        id: 'prod-006',
        sku: 'GEN-HELM-7700',
        name: 'DBI Sala Lad-Saf X3 Detachable Cable Safety Sleeve',
        description: 'Electrical hazard helmet with face shield and hearing protection',
        price: 129.99,
        category: 'general',
        type: 'helmet',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.9,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/m/d/md_1xgl7fga6kzp2.jpg'
    },
    {
        id: 'prod-007',
        sku: 'SOL-CABLE-4400',
        name: 'Safewaze Reusable Roof Anchor',
        description: 'Weatherproof cable trays and management for solar installations',
        price: 89.99,
        category: 'solar',
        type: 'tool',
        isOnSale: true,
        inStock: true,
        isBackOrder: false,
        rating: 4.3,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/a/2/a210400_pi.jpeg'
    },
    {
        id: 'prod-008',
        sku: 'WIND-BELT-6600',
        name: 'Ridgepro Roof Attachment Tool',
        description: 'Specialized safety belt for wind turbine tower climbing',
        price: 179.99,
        category: 'wind',
        type: 'safety-belt',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.6,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/r/p/rp-rp3q14-r.jpg'
    },
    {
        id: 'prod-009',
        sku: 'SOL-METER-1100',
        name: 'Guardian PitchPro Anchorage Connector',
        description: 'Digital multimeter with solar panel testing capabilities',
        price: 149.99,
        category: 'solar',
        type: 'tool',
        isOnSale: true,
        inStock: true,
        isBackOrder: true,
        rating: 4.4,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/p/i/pitchpro.jpg'
    },
    {
        id: 'prod-010',
        sku: 'WIND-TOOL-9900',
        name: 'Guardian 10600 Two-Way Universal Standing Seam Roof Clamp',
        description: 'Specialized tools for wind turbine maintenance and repair',
        price: 349.99,
        category: 'wind',
        type: 'tool',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.8,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/1/0/10600-front-72.jpg'
    },
    {
        id: 'prod-011',
        sku: 'GEN-LIGHT-1200',
        name: 'Streamlight 3AA ProPolymer Dualie Laser Flashlight',
        description: 'Intrinsically safe LED flashlight for hazardous locations',
        price: 112.5,
        category: 'general',
        type: 'lighting',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.7,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/d/u/dualielaser.jpg'
    },
    {
        id: 'prod-012',
        sku: 'SOL-BAG-5500',
        name: 'Klein Tools Tool Backpack',
        description: 'Solar technician backpack with multiple tool compartments',
        price: 139.99,
        category: 'solar',
        type: 'bag',
        isOnSale: true,
        inStock: false,
        isBackOrder: true,
        rating: 4.5,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/5/1/5185ora_photo.jpg'
    },
    {
        id: 'prod-013',
        sku: 'WIND-RADIO-7700',
        name: 'Motorola RMU2040 On-Site Two-Way Radio',
        description: 'Wind farm communication radio with noise cancellation',
        price: 289.0,
        category: 'wind',
        type: 'communication',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.6,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/r/m/rmu2040_rmm2050_rmu2043_right_lg_1.jpg'
    },
    {
        id: 'prod-014',
        sku: 'GEN-METER-8800',
        name: 'Fluke 87V Industrial Multimeter',
        description: 'True-RMS digital multimeter for electrical diagnostics',
        price: 429.99,
        category: 'general',
        type: 'meter',
        isOnSale: true,
        inStock: true,
        isBackOrder: false,
        rating: 4.9,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/f/-/f-87_v_01b_1500x1000.jpg'
    },
    {
        id: 'prod-015',
        sku: 'SOL-CUTTER-3300',
        name: 'Knipex 09 12 240 Cable Cutter',
        description: 'High-leverage cable cutter for solar panel installations',
        price: 67.25,
        category: 'solar',
        type: 'tool',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.8,
        imageUrl: 'https://www.gmesupply.com/media/catalog/product/farwest/765_2730_large.jpg'
    },
    {
        id: 'prod-016',
        sku: 'WIND-HARN-4400',
        name: 'Miller Revolution Harness',
        description: 'Tower climbing harness with dorsal D-ring',
        price: 319.99,
        category: 'wind',
        type: 'safety-belt',
        isOnSale: true,
        inStock: true,
        isBackOrder: true,
        rating: 4.7,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/r/d/rdt-qc-ubk.jpg'
    },
    {
        id: 'prod-017',
        sku: 'GEN-BOOTS-6600',
        name: 'Thorogood American Heritage Boots',
        description: 'Electrical hazard rated work boots with composite toe',
        price: 229.95,
        category: 'general',
        type: 'footwear',
        isOnSale: false,
        inStock: true,
        isBackOrder: false,
        rating: 4.9,
        imageUrl: 'https://www.gmesupply.com/media/gearcor/8/8044378-2.jpg'
    },
    {
        id: 'prod-018',
        sku: 'SOL-TESTER-9900',
        name: 'Gardner Bender Ground Fault Receptacle Tester and Circuit Analyzer',
        description: 'Solar circuit analyzer with GFCI test function',
        price: 199.0,
        category: 'solar',
        type: 'tester',
        isOnSale: false,
        inStock: false,
        isBackOrder: true,
        rating: 4.4,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/g/f/gfi-3501_hr.jpg'
    },
    {
        id: 'prod-019',
        sku: 'WIND-LANYARD-1100',
        name: '3M DBI Sala ShockWave2 Twin Leg Lanyard with Aluminum Connectors',
        description: 'Tower climbing lanyard with energy absorber',
        price: 89.99,
        category: 'wind',
        type: 'safety',
        isOnSale: true,
        inStock: true,
        isBackOrder: false,
        rating: 4.5,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/1/2/1244409.jpg'
    },
    {
        id: 'prod-020',
        sku: 'GEN-KNIFE-2200',
        name: 'Milwaukee Fastback Hawkbill Folding Knife',
        description: 'Compact utility knife with blade storage',
        price: 19.97,
        category: 'general',
        type: 'tool',
        isOnSale: true,
        inStock: true,
        isBackOrder: false,
        rating: 4.6,
        imageUrl: 'https://www.gmesupply.com/c/1024//media/catalog/product/4/8/48-22-1525_3.jpg'
    }
];
